### ISSUE TITLE
cx.view(net) works on Ubuntu, but the network has a weird appearance

### ISSUE THREAD

**Issue by jmarshallgit** [Calysto/conx#105]
<img width="277" alt="net" src="https://user-images.githubusercontent.com/30530366/35955511-c9eff67e-0c5d-11e8-98d1-cf253a61ba97.png">

**Comment by dsblank** [comment]
Is this output from the notebook, console, or both? Weird that it only does it on the hidden layers. Perhaps it is the number of units in those layers. If you make the hidden1 size smaller (say to as small as that of the output) does it still do that?

**Comment by dsblank** [comment]
Nothing we can do.
