### ISSUE TITLE
Network.set_dataset() takes a Dataset object

### ISSUE THREAD

**Issue by Neoanarika** [Calysto/conx#131]
I tried to copy the starter code in the github readme to a colab notebook running python3. However it gave me this error when I tried to run it. 

Network.set_dataset() takes a Dataset object.

Does anybody know how i can turn off this exception

**Comment by dsblank** [comment]
Thanks for pointing out the error. The line should be:
```
net.dataset.load(dataset)
```
and the README has been fixed.
