### ISSUE TITLE
hidden layer box seems way too big

### ISSUE THREAD

**Issue by jmarshallgit** [Calysto/conx#86]
cell 18 of MNIST notebook: visualization of network includes a 1000-unit hidden layer (viewed as 8 x 125) that seems way too big.
<img width="269" alt="screen shot 2018-02-02 at feb 2 9 58 19 pm" src="https://user-images.githubusercontent.com/30530366/35762420-4d9fea7c-0864-11e8-9c75-1bafeee661dc.png">

**Comment by dsblank** [comment]
It was, but because the code set image_maxdim. So all is cool
